### ISSUE TITLE
Cannot install Tigerbrew on x86 Leopard due to TLS problem

### ISSUE THREAD

**Issue by Amatarou-SUN** [mistydemeo/tigerbrew#918]
I'm trying to install Tigerbrew on an x86 Leopard, but I get a TLS error and can't install.

[Error message]

==> Downloading and Installing Homebrew...
curl: (35) error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
Failed during: /usr/bin/curl -Lk -1 https://archive.org/download/tigerbrew/portable-curl-7.58.0.tiger_i386.bottle.tar.gz -o /tmp/curl.tar.gz

**Comment by mistydemeo** [comment]
I think I've fixed this! You may not be able to `brew update` safely because of the bug, but if you edit `/usr/local/Library/Homebrew/cmd/vendor-install.sh` to replace the `https` URLs with `http`, it should work. Can you try that?

**Comment by Amatarou-SUN** [comment]
Wow!!! Working so fine!!! thank you for your fix!!!

**Comment by mistydemeo** [comment]
You're welcome! Please let me know if you have any other issues.

**Comment by gothickitty93** [comment]
Sorry to necro this bug, but I think it's still present. I used this fix on a PPC G4 Xserve running Mac OS X 10.5.9 Sorbet Leopard, and it worked. Perhaps this edit should be the default?

**Comment by sevan** [comment]
@gothickitty93 Are you working from an up to date Tigerbrew tree? [Misty commited the fix at the time](https://github.com/mistydemeo/tigerbrew/commit/3eb8081bf9f713feca8ee898145d4ee903186dfb) so it should be the default.

**Comment by gothickitty93** [comment]
[snippet.log](https://github.com/user-attachments/files/21207675/snippet.log)

> [@gothickitty93](https://github.com/gothickitty93) Are you working from an up to date Tigerbrew tree? [Misty commited the fix at the time](https://github.com/mistydemeo/tigerbrew/commit/3eb8081bf9f713feca8ee898145d4ee903186dfb) so it should be the default.

I hope so. I followed the install instructions on the main page to download the linked 'install' file and run it with ruby. Are these instructions no longer accurate?

It's strange, though. The fix is clearly committed (thanks for the link btw). I've attached a snippet from my console that shows both before and after the edit.

**Comment by mistydemeo** [comment]
Do you happen to have a copy of the error message left over from when you ran into it? Looks like I removed HTTPS downloads in the installer in 2023: 4f6c3e150fa6d0ad694d43eb8f5ab0b21e9b4456 So I'd *expect* it not to be trying to use HTTPS anymore, but maybe there's something more subtle that's broken?

Sorry for the inconvenience! And thanks for taking the time to come in and help us try to diagnose and fix it.

**Comment by gothickitty93** [comment]
All I got is that terminal snippet. Sorry!On Jul 13, 2025, at 9:26 PM, Misty De Méo ***@***.***> wrote:﻿mistydemeo left a comment (mistydemeo/tigerbrew#918)
Do you happen to have a copy of the error message left over from when you ran into it? Looks like I removed HTTPS downloads in the installer in 2023: 4f6c3e1 So I'd expect it not to be trying to use HTTPS anymore, but maybe there's something more subtle that's broken?
Sorry for the inconvenience! And thanks for taking the time to come in and help us try to diagnose and fix it.

**Comment by sevan** [comment]
The snippet shows that the request was clearly for HTTP, not HTTPS. I have a vague recollection of redirects happening on archive.org, but I can't put my finger on the exact details.

If you have git installed now, can you share the output of `git diff Library/Homebrew/cmd/vendor-install.sh` so we can see what change you made?

Can you also share the output from `/usr/local/opt/curl/bin/curl -I http://archive.org/download/tigerbrew/portable-curl-7.58.0-1.tiger_g3.bottle.tar.gz`

said snippet:
```
gothic-xserve:Public gothic_day$ brew install git
==> Please wait... tigers are now brewing
Downloading Tigerbrew's curl; this may take some time

==> Downloading http://archive.org/download/tigerbrew/portable-curl-7.58.0-1.tiger_g3.bottle.tar.gz
######################################################################## 100.0%
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Download failed: http://archive.org/download/tigerbrew/portable-curl-7.58.0-1.tiger_g3.bottle.tar.gz
Error: Failed to install vendor Curl.
gothic-xserve:Public gothic_day$ nano /usr/local/Library/Homebrew/cmd/vendor-install.sh
gothic-xserve:Public gothic_day$ brew update
==> Please wait... tigers are now brewing
Downloading Tigerbrew's curl; this may take some time

==> Downloading http://archive.org/download/tigerbrew/portable-curl-7.58.0-1.tiger_g3.bottle.tar.gz
######################################################################## 100.0%
==> Unpacking portable-curl-7.58.0-1.tiger_g3.bottle.tar.gz
==> Installing git
==> Installing dependencies for git: xz, gettext, curl-ca-bundle, perl, openssl3, pkg-config, ldns, zlib, openssh, lib
==> Installing git dependency: xz
```

**Comment by mistydemeo** [comment]
I think any remaining issues around this in new installs should be resolved by the installer now fetching curl from an HTTP-only mirror.
